=== mfmayer/gosk/api/json-schema/function-schema-v01.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Schema defintion for a semantic skill function.",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the function."
    },
    "description": {
      "type": "string",
      "description": "The description of the function."
    },
    "generator": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Comma separated names of generators that support this function. First found generator is used, so preferred generator should be first in the list."
        }
      },
      "additionalProperties": true
    },
    "parameters": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string",
            "description": "The description of the parameter."
          },
          "type": {
            "type": "string",
            "description": "The type of the parameter.",
            "enum": [
              "string",
              "number",
              "integer",
              "boolean",
              "array",
              "object"
            ]
          },
          "enum": {
            "type": "array",
            "description": "The list of possible values for the parameter.",
            "items": {
              "type": "string"
            }
          },
          "required": {
            "type": "boolean",
            "description": "Whether the parameter is required."
          },
          "default": {
            "type": [
              "string",
              "number",
              "integer",
              "boolean",
              "array",
              "object"
            ],
            "description": "The default value of the parameter."
          }
        }
      }
    }
  }
}

=== mfmayer/gosk/pkg/skills/assets/writer/translate/config.json
{
  "$schema": "https://raw.githubusercontent.com/mfmayer/gosk/main/api/json-schema/function-schema-v01.json",
  "name": "Translate",
  "description": "Translate a text into another language",
  "generator": {
    "name": "gpt35,default",
    "max_tokens": 1000,
    "temperature": 0.9,
    "top_p": 0.0,
    "presence_penalty": 0.0,
    "frequency_penalty": 0.0
  },
  "parameters": {
    "input": {
      "description": "Text to be translated"
    },
    "language": {
      "description": "Language to translate to"
    }
  }
}

=== mfmayer/gosk/pkg/skills/assets/fun/joke/config.json
{
  "$schema": "https://raw.githubusercontent.com/mfmayer/gosk/main/api/json-schema/function-schema-v01.json",
  "name": "Joke",
  "description": "Generate a funny joke",
  "generator": {
    "name": "gpt35,default",
    "max_tokens": 1000,
    "temperature": 0.9,
    "top_p": 0.0,
    "presence_penalty": 0.0,
    "frequency_penalty": 0.0
  },
  "parameters": {
    "data": {
      "description": "Joke subject",
      "defaultValue": ""
    },
    "style": {
      "description": "Joke style",
      "defaultValue": ""
    }
  }
}
