=== mfmayer/gosk/api/json-schema/skill-schema-v01.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Schema definition of a semantic skill.",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the skill."
    },
    "description": {
      "type": "string",
      "description": "The description of the skill."
    },
    "plannable": {
      "type": "boolean",
      "description": "Indicates whether the skill can be used in a plan."
    },
    "generators": {
      "type": "object",
      "description": "Map of generators used by the skill functions.",
      "additionalProperties": {
        "type": "object",
        "description": "Generator defined by a typeID and according config propoerties.",
        "properties": {
          "typeID": {
            "type": "string",
            "description": "Generator Type Identifier to be used to create this generator."
          },
          "config": {
            "type": "object",
            "description": "Configuration parameters that will be given to the generator factory with according typeID to create this generator.",
            "additionalProperties": true
          }
        }
      }
    }
  }
}

=== mfmayer/gosk/pkg/skills/openweathermap/assets/config.json
{
  "$schema": "https://raw.githubusercontent.com/mfmayer/gosk/main/api/json-schema/skill-schema-v01.json",
  "name": "weather",
  "description": "A skill that allows to access weather information and provide current and forecast weather data.",
  "plannable": true,
  "generators": {
    "gpt-3.5-turbo": {
      "model": "gpt-3.5-turbo",
      "temperature": 0.7,
      "max_tokens": 64,
      "top_p": 1,
      "frequency_penalty": 0,
      "presence_penalty": 0
    }
  }
}
